// constants/completeRosters.js
// Complete NFL Team Rosters - 52 cards per team (A through 2)
// Total: 32 teams × 52 cards = 1,664 unique player cards

export const NFL_TEAMS = [
  { id: 'ari', name: 'Arizona Cardinals', emoji: '🏜️', shortName: 'Cardinals' },
  { id: 'atl', name: 'Atlanta Falcons', emoji: '🦅', shortName: 'Falcons' },
  { id: 'bal', name: 'Baltimore Ravens', emoji: '🐦‍⬛', shortName: 'Ravens' },
  { id: 'buf', name: 'Buffalo Bills', emoji: '🐃', shortName: 'Bills' },
  { id: 'car', name: 'Carolina Panthers', emoji: '🐱', shortName: 'Panthers' },
  { id: 'chi', name: 'Chicago Bears', emoji: '🐻', shortName: 'Bears' },
  { id: 'cin', name: 'Cincinnati Bengals', emoji: '🐯', shortName: 'Bengals' },
  { id: 'cle', name: 'Cleveland Browns', emoji: '🏈', shortName: 'Browns' },
  { id: 'dal', name: 'Dallas Cowboys', emoji: '⭐', shortName: 'Cowboys' },
  { id: 'den', name: 'Denver Broncos', emoji: '🐴', shortName: 'Broncos' },
  { id: 'det', name: 'Detroit Lions', emoji: '🦁', shortName: 'Lions' },
  { id: 'gb', name: 'Green Bay Packers', emoji: '🧀', shortName: 'Packers' },
  { id: 'hou', name: 'Houston Texans', emoji: '🤠', shortName: 'Texans' },
  { id: 'ind', name: 'Indianapolis Colts', emoji: '🐎', shortName: 'Colts' },
  { id: 'jac', name: 'Jacksonville Jaguars', emoji: '🐆', shortName: 'Jaguars' },
  { id: 'kc', name: 'Kansas City Chiefs', emoji: '🏹', shortName: 'Chiefs' },
  { id: 'lv', name: 'Las Vegas Raiders', emoji: '☠️', shortName: 'Raiders' },
  { id: 'lac', name: 'Los Angeles Chargers', emoji: '⚡', shortName: 'Chargers' },
  { id: 'lar', name: 'Los Angeles Rams', emoji: '🐏', shortName: 'Rams' },
  { id: 'mia', name: 'Miami Dolphins', emoji: '🐬', shortName: 'Dolphins' },
  { id: 'min', name: 'Minnesota Vikings', emoji: '⚔️', shortName: 'Vikings' },
  { id: 'ne', name: 'New England Patriots', emoji: '🇺🇸', shortName: 'Patriots' },
  { id: 'no', name: 'New Orleans Saints', emoji: '⚜️', shortName: 'Saints' },
  { id: 'nyg', name: 'New York Giants', emoji: '🗽', shortName: 'Giants' },
  { id: 'nyj', name: 'New York Jets', emoji: '✈️', shortName: 'Jets' },
  { id: 'phi', name: 'Philadelphia Eagles', emoji: '🦅', shortName: 'Eagles' },
  { id: 'pit', name: 'Pittsburgh Steelers', emoji: '⚫', shortName: 'Steelers' },
  { id: 'sf', name: 'San Francisco 49ers', emoji: '🏈', shortName: '49ers' },
  { id: 'sea', name: 'Seattle Seahawks', emoji: '⚓', shortName: 'Seahawks' },
  { id: 'tb', name: 'Tampa Bay Buccaneers', emoji: '🏴‍☠️', shortName: 'Buccaneers' },
  { id: 'ten', name: 'Tennessee Titans', emoji: '⚔️', shortName: 'Titans' },
  { id: 'was', name: 'Washington Commanders', emoji: '⭐', shortName: 'Commanders' },
];

export const TEAM_ROSTERS = {
  // ========== NFC WEST ==========
  ari: {
    'A': { name: 'Larry Fitzgerald', position: 'WR', era: 'Legend' },
    'K': { name: 'Kyler Murray', position: 'QB', era: 'Current' },
    'Q': { name: 'Aeneas Williams', position: 'CB', era: 'Legend' },
    'J': { name: 'Budda Baker', position: 'S', era: 'Current' },
    '10': { name: 'James Conner', position: 'RB', era: 'Current' },
    '9': { name: 'Marvin Harrison Jr.', position: 'WR', era: 'Current' },
    '8': { name: 'Pat Tillman', position: 'S', era: 'Legend' },
    '7': { name: 'Trey McBride', position: 'TE', era: 'Current' },
    '6': { name: 'Adrian Wilson', position: 'S', era: 'Legend' },
    '5': { name: 'Paris Johnson Jr.', position: 'OT', era: 'Current' },
    '4': { name: 'Dan Dierdorf', position: 'OT', era: 'Legend' },
    '3': { name: 'Jalen Thompson', position: 'S', era: 'Current' },
    '2': { name: 'Matt Prater', position: 'K', era: 'Current' }
  },
  lar: {
    'A': { name: 'Aaron Donald', position: 'DT', era: 'Legend' },
    'K': { name: 'Matthew Stafford', position: 'QB', era: 'Current' },
    'Q': { name: 'Eric Dickerson', position: 'RB', era: 'Legend' },
    'J': { name: 'Cooper Kupp', position: 'WR', era: 'Current' },
    '10': { name: 'Puka Nacua', position: 'WR', era: 'Current' },
    '9': { name: 'Jack Youngblood', position: 'DE', era: 'Legend' },
    '8': { name: 'Kyren Williams', position: 'RB', era: 'Current' },
    '7': { name: 'Jared Verse', position: 'DE', era: 'Current' },
    '6': { name: 'Marshall Faulk', position: 'RB', era: 'Legend' },
    '5': { name: 'Kobie Turner', position: 'DT', era: 'Current' },
    '4': { name: 'Deacon Jones', position: 'DE', era: 'Legend' },
    '3': { name: 'Quentin Lake', position: 'S', era: 'Current' },
    '2': { name: 'Joshua Karty', position: 'K', era: 'Current' }
  },
  sf: {
    'A': { name: 'Jerry Rice', position: 'WR', era: 'Legend' },
    'K': { name: 'Brock Purdy', position: 'QB', era: 'Current' },
    'Q': { name: 'Joe Montana', position: 'QB', era: 'Legend' },
    'J': { name: 'Christian McCaffrey', position: 'RB', era: 'Current' },
    '10': { name: 'Nick Bosa', position: 'DE', era: 'Current' },
    '9': { name: 'Steve Young', position: 'QB', era: 'Legend' },
    '8': { name: 'Fred Warner', position: 'LB', era: 'Current' },
    '7': { name: 'George Kittle', position: 'TE', era: 'Current' },
    '6': { name: 'Ronnie Lott', position: 'S', era: 'Legend' },
    '5': { name: 'Deebo Samuel', position: 'WR', era: 'Current' },
    '4': { name: 'Patrick Willis', position: 'LB', era: 'Legend' },
    '3': { name: 'Trent Williams', position: 'OT', era: 'Current' },
    '2': { name: 'Jake Moody', position: 'K', era: 'Current' }
  },
  sea: {
    'A': { name: 'Steve Largent', position: 'WR', era: 'Legend' },
    'K': { name: 'Russell Wilson', position: 'QB', era: 'Legend' },
    'Q': { name: 'Walter Jones', position: 'OT', era: 'Legend' },
    'J': { name: 'DK Metcalf', position: 'WR', era: 'Current' },
    '10': { name: 'Bobby Wagner', position: 'LB', era: 'Current' },
    '9': { name: 'Cortez Kennedy', position: 'DT', era: 'Legend' },
    '8': { name: 'Kenneth Walker III', position: 'RB', era: 'Current' },
    '7': { name: 'Tyler Lockett', position: 'WR', era: 'Current' },
    '6': { name: 'Kenny Easley', position: 'S', era: 'Legend' },
    '5': { name: 'Devon Witherspoon', position: 'CB', era: 'Current' },
    '4': { name: 'Richard Sherman', position: 'CB', era: 'Legend' },
    '3': { name: 'Julian Love', position: 'S', era: 'Current' },
    '2': { name: 'Jason Myers', position: 'K', era: 'Current' }
  },

  // ========== NFC NORTH ==========
  chi: {
    'A': { name: 'Walter Payton', position: 'RB', era: 'Legend' },
    'K': { name: 'Dick Butkus', position: 'LB', era: 'Legend' },
    'Q': { name: 'Mike Singletary', position: 'LB', era: 'Legend' },
    'J': { name: 'Caleb Williams', position: 'QB', era: 'Current' },
    '10': { name: 'D.J. Moore', position: 'WR', era: 'Current' },
    '9': { name: 'Gale Sayers', position: 'RB', era: 'Legend' },
    '8': { name: 'Montez Sweat', position: 'DE', era: 'Current' },
    '7': { name: 'Brian Urlacher', position: 'LB', era: 'Legend' },
    '6': { name: 'Devon Hester', position: 'KR', era: 'Legend' },
    '5': { name: 'Jaylon Johnson', position: 'CB', era: 'Current' },
    '4': { name: 'Dan Hampton', position: 'DT', era: 'Legend' },
    '3': { name: 'Keenan Allen', position: 'WR', era: 'Current' },
    '2': { name: 'Cairo Santos', position: 'K', era: 'Current' }
  },
  det: {
    'A': { name: 'Barry Sanders', position: 'RB', era: 'Legend' },
    'K': { name: 'Calvin Johnson', position: 'WR', era: 'Legend' },
    'Q': { name: 'Jared Goff', position: 'QB', era: 'Current' },
    'J': { name: 'Amon-Ra St. Brown', position: 'WR', era: 'Current' },
    '10': { name: 'Aidan Hutchinson', position: 'DE', era: 'Current' },
    '9': { name: 'Joe Schmidt', position: 'LB', era: 'Legend' },
    '8': { name: 'Jahmyr Gibbs', position: 'RB', era: 'Current' },
    '7': { name: 'Sam LaPorta', position: 'TE', era: 'Current' },
    '6': { name: 'Lem Barney', position: 'CB', era: 'Legend' },
    '5': { name: 'Brian Branch', position: 'S', era: 'Current' },
    '4': { name: 'Alex Karras', position: 'DT', era: 'Legend' },
    '3': { name: 'Kerby Joseph', position: 'S', era: 'Current' },
    '2': { name: 'Jake Bates', position: 'K', era: 'Current' }
  },
  gb: {
    'A': { name: 'Brett Favre', position: 'QB', era: 'Legend' },
    'K': { name: 'Aaron Rodgers', position: 'QB', era: 'Legend' },
    'Q': { name: 'Reggie White', position: 'DE', era: 'Legend' },
    'J': { name: 'Jordan Love', position: 'QB', era: 'Current' },
    '10': { name: 'Josh Jacobs', position: 'RB', era: 'Current' },
    '9': { name: 'Ray Nitschke', position: 'LB', era: 'Legend' },
    '8': { name: 'Jaire Alexander', position: 'CB', era: 'Current' },
    '7': { name: 'Rashan Gary', position: 'DE', era: 'Current' },
    '6': { name: 'Bart Starr', position: 'QB', era: 'Legend' },
    '5': { name: 'Christian Watson', position: 'WR', era: 'Current' },
    '4': { name: 'Don Hutson', position: 'WR', era: 'Legend' },
    '3': { name: 'Xavier McKinney', position: 'S', era: 'Current' },
    '2': { name: 'Brandon McManus', position: 'K', era: 'Current' }
  },
  min: {
    'A': { name: 'Randy Moss', position: 'WR', era: 'Legend' },
    'K': { name: 'Cris Carter', position: 'WR', era: 'Legend' },
    'Q': { name: 'Fran Tarkenton', position: 'QB', era: 'Legend' },
    'J': { name: 'Justin Jefferson', position: 'WR', era: 'Current' },
    '10': { name: 'Adrian Peterson', position: 'RB', era: 'Legend' },
    '9': { name: 'Alan Page', position: 'DT', era: 'Legend' },
    '8': { name: 'Jordan Addison', position: 'WR', era: 'Current' },
    '7': { name: 'John Randle', position: 'DT', era: 'Legend' },
    '6': { name: 'Harrison Smith', position: 'S', era: 'Current' },
    '5': { name: 'T.J. Hockenson', position: 'TE', era: 'Current' },
    '4': { name: 'Paul Krause', position: 'S', era: 'Legend' },
    '3': { name: 'Jonathan Greenard', position: 'DE', era: 'Current' },
    '2': { name: 'Will Reichard', position: 'K', era: 'Current' }
  },

  // ========== NFC EAST ==========
  dal: {
    'A': { name: 'Emmitt Smith', position: 'RB', era: 'Legend' },
    'K': { name: 'Troy Aikman', position: 'QB', era: 'Legend' },
    'Q': { name: 'Michael Irvin', position: 'WR', era: 'Legend' },
    'J': { name: 'Dak Prescott', position: 'QB', era: 'Current' },
    '10': { name: 'Micah Parsons', position: 'LB', era: 'Current' },
    '9': { name: 'DeMarcus Ware', position: 'LB', era: 'Legend' },
    '8': { name: 'CeeDee Lamb', position: 'WR', era: 'Current' },
    '7': { name: 'Tony Dorsett', position: 'RB', era: 'Legend' },
    '6': { name: 'Randy White', position: 'DT', era: 'Legend' },
    '5': { name: 'Trevon Diggs', position: 'CB', era: 'Current' },
    '4': { name: 'Larry Allen', position: 'G', era: 'Legend' },
    '3': { name: 'Zack Martin', position: 'G', era: 'Current' },
    '2': { name: 'Brandon Aubrey', position: 'K', era: 'Current' }
  },
  nyg: {
    'A': { name: 'Lawrence Taylor', position: 'LB', era: 'Legend' },
    'K': { name: 'Eli Manning', position: 'QB', era: 'Legend' },
    'Q': { name: 'Michael Strahan', position: 'DE', era: 'Legend' },
    'J': { name: 'Saquon Barkley', position: 'RB', era: 'Current' },
    '10': { name: 'Dexter Lawrence', position: 'DT', era: 'Current' },
    '9': { name: 'Harry Carson', position: 'LB', era: 'Legend' },
    '8': { name: 'Malik Nabers', position: 'WR', era: 'Current' },
    '7': { name: 'Kayvon Thibodeaux', position: 'DE', era: 'Current' },
    '6': { name: 'Phil Simms', position: 'QB', era: 'Legend' },
    '5': { name: 'Bobby Okereke', position: 'LB', era: 'Current' },
    '4': { name: 'Carl Banks', position: 'LB', era: 'Legend' },
    '3': { name: 'Jason Pinnock', position: 'S', era: 'Current' },
    '2': { name: 'Graham Gano', position: 'K', era: 'Current' }
  },
  phi: {
    'A': { name: 'Reggie White', position: 'DE', era: 'Legend' },
    'K': { name: 'Brian Dawkins', position: 'S', era: 'Legend' },
    'Q': { name: 'Jalen Hurts', position: 'QB', era: 'Current' },
    'J': { name: 'Chuck Bednarik', position: 'LB', era: 'Legend' },
    '10': { name: 'A.J. Brown', position: 'WR', era: 'Current' },
    '9': { name: 'Steve Van Buren', position: 'RB', era: 'Legend' },
    '8': { name: 'Saquon Barkley', position: 'RB', era: 'Current' },
    '7': { name: 'Lane Johnson', position: 'OT', era: 'Current' },
    '6': { name: 'Harold Carmichael', position: 'WR', era: 'Legend' },
    '5': { name: 'Devonta Smith', position: 'WR', era: 'Current' },
    '4': { name: 'Tommy McDonald', position: 'WR', era: 'Legend' },
    '3': { name: 'Jalen Carter', position: 'DT', era: 'Current' },
    '2': { name: 'Jake Elliott', position: 'K', era: 'Current' }
  },
  was: {
    'A': { name: 'Darrell Green', position: 'CB', era: 'Legend' },
    'K': { name: 'John Riggins', position: 'RB', era: 'Legend' },
    'Q': { name: 'Art Monk', position: 'WR', era: 'Legend' },
    'J': { name: 'Jayden Daniels', position: 'QB', era: 'Current' },
    '10': { name: 'Terry McLaurin', position: 'WR', era: 'Current' },
    '9': { name: 'Sam Huff', position: 'LB', era: 'Legend' },
    '8': { name: 'Brian Robinson Jr.', position: 'RB', era: 'Current' },
    '7': { name: 'Jonathan Allen', position: 'DT', era: 'Current' },
    '6': { name: 'Sean Taylor', position: 'S', era: 'Legend' },
    '5': { name: 'Daron Payne', position: 'DT', era: 'Current' },
    '4': { name: 'Sonny Jurgensen', position: 'QB', era: 'Legend' },
    '3': { name: 'Bobby Wagner', position: 'LB', era: 'Current' },
    '2': { name: 'Austin Seibert', position: 'K', era: 'Current' }
  },

  // ========== AFC WEST ==========
  den: {
    'A': { name: 'John Elway', position: 'QB', era: 'Legend' },
    'K': { name: 'Terrell Davis', position: 'RB', era: 'Legend' },
    'Q': { name: 'Champ Bailey', position: 'CB', era: 'Legend' },
    'J': { name: 'Patrick Surtain II', position: 'CB', era: 'Current' },
    '10': { name: 'Javonte Williams', position: 'RB', era: 'Current' },
    '9': { name: 'Shannon Sharpe', position: 'TE', era: 'Legend' },
    '8': { name: 'Courtland Sutton', position: 'WR', era: 'Current' },
    '7': { name: 'Bo Nix', position: 'QB', era: 'Current' },
    '6': { name: 'Steve Atwater', position: 'S', era: 'Legend' },
    '5': { name: 'Nik Bonitto', position: 'LB', era: 'Current' },
    '4': { name: 'Randy Gradishar', position: 'LB', era: 'Legend' },
    '3': { name: 'Quinn Meinerz', position: 'G', era: 'Current' },
    '2': { name: 'Wil Lutz', position: 'K', era: 'Current' }
  },
  kc: {
    'A': { name: 'Patrick Mahomes', position: 'QB', era: 'Current' },
    'K': { name: 'Travis Kelce', position: 'TE', era: 'Current' },
    'Q': { name: 'Len Dawson', position: 'QB', era: 'Legend' },
    'J': { name: 'Derrick Thomas', position: 'LB', era: 'Legend' },
    '10': { name: 'Chris Jones', position: 'DT', era: 'Current' },
    '9': { name: 'Willie Lanier', position: 'LB', era: 'Legend' },
    '8': { name: 'Isiah Pacheco', position: 'RB', era: 'Current' },
    '7': { name: 'Tony Gonzalez', position: 'TE', era: 'Legend' },
    '6': { name: 'Bobby Bell', position: 'LB', era: 'Legend' },
    '5': { name: 'Trent McDuffie', position: 'CB', era: 'Current' },
    '4': { name: 'Buck Buchanan', position: 'DT', era: 'Legend' },
    '3': { name: 'George Karlaftis', position: 'DE', era: 'Current' },
    '2': { name: 'Harrison Butker', position: 'K', era: 'Current' }
  },
  lv: {
    'A': { name: 'Tim Brown', position: 'WR', era: 'Legend' },
    'K': { name: 'Marcus Allen', position: 'RB', era: 'Legend' },
    'Q': { name: 'Howie Long', position: 'DE', era: 'Legend' },
    'J': { name: 'Maxx Crosby', position: 'DE', era: 'Current' },
    '10': { name: 'Davante Adams', position: 'WR', era: 'Current' },
    '9': { name: 'Fred Biletnikoff', position: 'WR', era: 'Legend' },
    '8': { name: 'Brock Bowers', position: 'TE', era: 'Current' },
    '7': { name: 'Jack Tatum', position: 'S', era: 'Legend' },
    '6': { name: 'Bo Jackson', position: 'RB', era: 'Legend' },
    '5': { name: 'Jakobi Meyers', position: 'WR', era: 'Current' },
    '4': { name: 'Gene Upshaw', position: 'G', era: 'Legend' },
    '3': { name: 'Christian Wilkins', position: 'DT', era: 'Current' },
    '2': { name: 'Daniel Carlson', position: 'K', era: 'Current' }
  },
  lac: {
    'A': { name: 'LaDainian Tomlinson', position: 'RB', era: 'Legend' },
    'K': { name: 'Dan Fouts', position: 'QB', era: 'Legend' },
    'Q': { name: 'Junior Seau', position: 'LB', era: 'Legend' },
    'J': { name: 'Justin Herbert', position: 'QB', era: 'Current' },
    '10': { name: 'Khalil Mack', position: 'LB', era: 'Current' },
    '9': { name: 'Antonio Gates', position: 'TE', era: 'Legend' },
    '8': { name: 'Derwin James', position: 'S', era: 'Current' },
    '7': { name: 'Joey Bosa', position: 'DE', era: 'Current' },
    '6': { name: 'Lance Alworth', position: 'WR', era: 'Legend' },
    '5': { name: 'Quentin Johnston', position: 'WR', era: 'Current' },
    '4': { name: 'Kellen Winslow', position: 'TE', era: 'Legend' },
    '3': { name: 'Rashawn Slater', position: 'OT', era: 'Current' },
    '2': { name: 'Cameron Dicker', position: 'K', era: 'Current' }
  },

  // ========== AFC NORTH ==========
  bal: {
    'A': { name: 'Ray Lewis', position: 'LB', era: 'Legend' },
    'K': { name: 'Ed Reed', position: 'S', era: 'Legend' },
    'Q': { name: 'Lamar Jackson', position: 'QB', era: 'Current' },
    'J': { name: 'Jonathan Ogden', position: 'OT', era: 'Legend' },
    '10': { name: 'Derrick Henry', position: 'RB', era: 'Current' },
    '9': { name: 'Terrell Suggs', position: 'LB', era: 'Legend' },
    '8': { name: 'Roquan Smith', position: 'LB', era: 'Current' },
    '7': { name: 'Justin Tucker', position: 'K', era: 'Current' },
    '6': { name: 'Jamal Lewis', position: 'RB', era: 'Legend' },
    '5': { name: 'Zay Flowers', position: 'WR', era: 'Current' },
    '4': { name: 'Rod Woodson', position: 'CB', era: 'Legend' },
    '3': { name: 'Kyle Hamilton', position: 'S', era: 'Current' },
    '2': { name: 'Marlon Humphrey', position: 'CB', era: 'Current' }
  },
  cin: {
    'A': { name: 'Anthony Munoz', position: 'OT', era: 'Legend' },
    'K': { name: 'Joe Burrow', position: 'QB', era: 'Current' },
    'Q': { name: 'Ja\'Marr Chase', position: 'WR', era: 'Current' },
    'J': { name: 'Tee Higgins', position: 'WR', era: 'Current' },
    '10': { name: 'Ken Riley', position: 'CB', era: 'Legend' },
    '9': { name: 'Boomer Esiason', position: 'QB', era: 'Legend' },
    '8': { name: 'Trey Hendrickson', position: 'DE', era: 'Current' },
    '7': { name: 'Logan Wilson', position: 'LB', era: 'Current' },
    '6': { name: 'Chad Johnson', position: 'WR', era: 'Legend' },
    '5': { name: 'Mike Hilton', position: 'CB', era: 'Current' },
    '4': { name: 'Isaac Curtis', position: 'WR', era: 'Legend' },
    '3': { name: 'Dax Hill', position: 'S', era: 'Current' },
    '2': { name: 'Evan McPherson', position: 'K', era: 'Current' }
  },
  cle: {
    'A': { name: 'Jim Brown', position: 'RB', era: 'Legend' },
    'K': { name: 'Otto Graham', position: 'QB', era: 'Legend' },
    'Q': { name: 'Myles Garrett', position: 'DE', era: 'Current' },
    'J': { name: 'Nick Chubb', position: 'RB', era: 'Current' },
    '10': { name: 'Joe Thomas', position: 'OT', era: 'Legend' },
    '9': { name: 'Clay Matthews', position: 'LB', era: 'Legend' },
    '8': { name: 'Denzel Ward', position: 'CB', era: 'Current' },
    '7': { name: 'Amari Cooper', position: 'WR', era: 'Current' },
    '6': { name: 'Ozzie Newsome', position: 'TE', era: 'Legend' },
    '5': { name: 'David Njoku', position: 'TE', era: 'Current' },
    '4': { name: 'Leroy Kelly', position: 'RB', era: 'Legend' },
    '3': { name: 'Jeremiah Owusu-Koramoah', position: 'LB', era: 'Current' },
    '2': { name: 'Dustin Hopkins', position: 'K', era: 'Current' }
  },
  pit: {
    'A': { name: 'Mean Joe Greene', position: 'DT', era: 'Legend' },
    'K': { name: 'Terry Bradshaw', position: 'QB', era: 'Legend' },
    'Q': { name: 'T.J. Watt', position: 'LB', era: 'Current' },
    'J': { name: 'Ben Roethlisberger', position: 'QB', era: 'Legend' },
    '10': { name: 'Jerome Bettis', position: 'RB', era: 'Legend' },
    '9': { name: 'Jack Lambert', position: 'LB', era: 'Legend' },
    '8': { name: 'Minkah Fitzpatrick', position: 'S', era: 'Current' },
    '7': { name: 'Najee Harris', position: 'RB', era: 'Current' },
    '6': { name: 'Lynn Swann', position: 'WR', era: 'Legend' },
    '5': { name: 'George Pickens', position: 'WR', era: 'Current' },
    '4': { name: 'Mel Blount', position: 'CB', era: 'Legend' },
    '3': { name: 'Alex Highsmith', position: 'LB', era: 'Current' },
    '2': { name: 'Chris Boswell', position: 'K', era: 'Current' }
  },

  // ========== AFC EAST ==========
  buf: {
    'A': { name: 'Jim Kelly', position: 'QB', era: 'Legend' },
    'K': { name: 'Bruce Smith', position: 'DE', era: 'Legend' },
    'Q': { name: 'Josh Allen', position: 'QB', era: 'Current' },
    'J': { name: 'Stefon Diggs', position: 'WR', era: 'Current' },
    '10': { name: 'Thurman Thomas', position: 'RB', era: 'Legend' },
    '9': { name: 'Andre Reed', position: 'WR', era: 'Legend' },
    '8': { name: 'James Cook', position: 'RB', era: 'Current' },
    '7': { name: 'Von Miller', position: 'LB', era: 'Current' },
    '6': { name: 'Cornelius Bennett', position: 'LB', era: 'Legend' },
    '5': { name: 'Matt Milano', position: 'LB', era: 'Current' },
    '4': { name: 'Darren Woodson', position: 'S', era: 'Legend' },
    '3': { name: 'Dalton Kincaid', position: 'TE', era: 'Current' },
    '2': { name: 'Tyler Bass', position: 'K', era: 'Current' }
  },
  mia: {
    'A': { name: 'Dan Marino', position: 'QB', era: 'Legend' },
    'K': { name: 'Tyreek Hill', position: 'WR', era: 'Current' },
    'Q': { name: 'Jason Taylor', position: 'DE', era: 'Legend' },
    'J': { name: 'Tua Tagovailoa', position: 'QB', era: 'Current' },
    '10': { name: 'Zach Thomas', position: 'LB', era: 'Legend' },
    '9': { name: 'Larry Csonka', position: 'RB', era: 'Legend' },
    '8': { name: 'Jaylen Waddle', position: 'WR', era: 'Current' },
    '7': { name: 'Bob Griese', position: 'QB', era: 'Legend' },
    '6': { name: 'Paul Warfield', position: 'WR', era: 'Legend' },
    '5': { name: 'Jaelan Phillips', position: 'DE', era: 'Current' },
    '4': { name: 'Dwight Stephenson', position: 'C', era: 'Legend' },
    '3': { name: 'Jevon Holland', position: 'S', era: 'Current' },
    '2': { name: 'Jason Sanders', position: 'K', era: 'Current' }
  },
  ne: {
    'A': { name: 'Tom Brady', position: 'QB', era: 'Legend' },
    'K': { name: 'Rob Gronkowski', position: 'TE', era: 'Legend' },
    'Q': { name: 'Randy Moss', position: 'WR', era: 'Legend' },
    'J': { name: 'Drake Maye', position: 'QB', era: 'Current' },
    '10': { name: 'Lawrence Taylor', position: 'LB', era: 'Legend' },
    '9': { name: 'Mike Vrabel', position: 'LB', era: 'Legend' },
    '8': { name: 'Rhamondre Stevenson', position: 'RB', era: 'Current' },
    '7': { name: 'John Hannah', position: 'G', era: 'Legend' },
    '6': { name: 'Ty Law', position: 'CB', era: 'Legend' },
    '5': { name: 'Christian Gonzalez', position: 'CB', era: 'Current' },
    '4': { name: 'Andre Tippett', position: 'LB', era: 'Legend' },
    '3': { name: 'Kyle Dugger', position: 'S', era: 'Current' },
    '2': { name: 'Adam Vinatieri', position: 'K', era: 'Legend' }
  },
  nyj: {
    'A': { name: 'Joe Namath', position: 'QB', era: 'Legend' },
    'K': { name: 'Darrelle Revis', position: 'CB', era: 'Legend' },
    'Q': { name: 'Aaron Rodgers', position: 'QB', era: 'Current' },
    'J': { name: 'Sauce Gardner', position: 'CB', era: 'Current' },
    '10': { name: 'Curtis Martin', position: 'RB', era: 'Legend' },
    '9': { name: 'Don Maynard', position: 'WR', era: 'Legend' },
    '8': { name: 'Breece Hall', position: 'RB', era: 'Current' },
    '7': { name: 'Quinnen Williams', position: 'DT', era: 'Current' },
    '6': { name: 'Joe Klecko', position: 'DT', era: 'Legend' },
    '5': { name: 'Garrett Wilson', position: 'WR', era: 'Current' },
    '4': { name: 'Mark Gastineau', position: 'DE', era: 'Legend' },
    '3': { name: 'C.J. Mosley', position: 'LB', era: 'Current' },
    '2': { name: 'Greg Zuerlein', position: 'K', era: 'Current' }
  },

  // ========== AFC SOUTH ==========
  hou: {
    'A': { name: 'J.J. Watt', position: 'DE', era: 'Legend' },
    'K': { name: 'Andre Johnson', position: 'WR', era: 'Legend' },
    'Q': { name: 'C.J. Stroud', position: 'QB', era: 'Current' },
    'J': { name: 'Will Anderson Jr.', position: 'DE', era: 'Current' },
    '10': { name: 'Arian Foster', position: 'RB', era: 'Legend' },
    '9': { name: 'DeMeco Ryans', position: 'LB', era: 'Legend' },
    '8': { name: 'Nico Collins', position: 'WR', era: 'Current' },
    '7': { name: 'Joe Mixon', position: 'RB', era: 'Current' },
    '6': { name: 'Tank Dell', position: 'WR', era: 'Current' },
    '5': { name: 'Derek Stingley Jr.', position: 'CB', era: 'Current' },
    '4': { name: 'Mario Williams', position: 'DE', era: 'Legend' },
    '3': { name: 'Dalton Schultz', position: 'TE', era: 'Current' },
    '2': { name: 'Ka\'imi Fairbairn', position: 'K', era: 'Current' }
  },
  ind: {
    'A': { name: 'Peyton Manning', position: 'QB', era: 'Legend' },
    'K': { name: 'Marvin Harrison', position: 'WR', era: 'Legend' },
    'Q': { name: 'Jonathan Taylor', position: 'RB', era: 'Current' },
    'J': { name: 'Reggie Wayne', position: 'WR', era: 'Legend' },
    '10': { name: 'Dwight Freeney', position: 'DE', era: 'Legend' },
    '9': { name: 'Anthony Richardson', position: 'QB', era: 'Current' },
    '8': { name: 'Marshall Faulk', position: 'RB', era: 'Legend' },
    '7': { name: 'Quenton Nelson', position: 'G', era: 'Current' },
    '6': { name: 'Robert Mathis', position: 'LB', era: 'Legend' },
    '5': { name: 'Michael Pittman Jr.', position: 'WR', era: 'Current' },
    '4': { name: 'Jeff Saturday', position: 'C', era: 'Legend' },
    '3': { name: 'DeForest Buckner', position: 'DT', era: 'Current' },
    '2': { name: 'Matt Gay', position: 'K', era: 'Current' }
  },
  jac: {
    'A': { name: 'Tony Boselli', position: 'OT', era: 'Legend' },
    'K': { name: 'Fred Taylor', position: 'RB', era: 'Legend' },
    'Q': { name: 'Trevor Lawrence', position: 'QB', era: 'Current' },
    'J': { name: 'Josh Allen', position: 'DE', era: 'Current' },
    '10': { name: 'Jimmy Smith', position: 'WR', era: 'Legend' },
    '9': { name: 'Travis Etienne', position: 'RB', era: 'Current' },
    '8': { name: 'Maurice Jones-Drew', position: 'RB', era: 'Legend' },
    '7': { name: 'Brian Thomas Jr.', position: 'WR', era: 'Current' },
    '6': { name: 'Calais Campbell', position: 'DE', era: 'Legend' },
    '5': { name: 'Christian Kirk', position: 'WR', era: 'Current' },
    '4': { name: 'Marcus Stroud', position: 'DT', era: 'Legend' },
    '3': { name: 'Travon Walker', position: 'DE', era: 'Current' },
    '2': { name: 'Cam Little', position: 'K', era: 'Current' }
  },
  ten: {
    'A': { name: 'Steve McNair', position: 'QB', era: 'Legend' },
    'K': { name: 'Eddie George', position: 'RB', era: 'Legend' },
    'Q': { name: 'Derrick Henry', position: 'RB', era: 'Legend' },
    'J': { name: 'Will Levis', position: 'QB', era: 'Current' },
    '10': { name: 'Bruce Matthews', position: 'OL', era: 'Legend' },
    '9': { name: 'Jevon Kearse', position: 'DE', era: 'Legend' },
    '8': { name: 'Jeffery Simmons', position: 'DT', era: 'Current' },
    '7': { name: 'Tony Pollard', position: 'RB', era: 'Current' },
    '6': { name: 'DeAndre Hopkins', position: 'WR', era: 'Current' },
    '5': { name: 'Harold Landry', position: 'LB', era: 'Current' },
    '4': { name: 'Warren Moon', position: 'QB', era: 'Legend' },
    '3': { name: 'Calvin Ridley', position: 'WR', era: 'Current' },
    '2': { name: 'Nick Folk', position: 'K', era: 'Current' }
  },

  // ========== NFC SOUTH ==========
  atl: {
    'A': { name: 'Matt Ryan', position: 'QB', era: 'Legend' },
    'K': { name: 'Julio Jones', position: 'WR', era: 'Legend' },
    'Q': { name: 'Bijan Robinson', position: 'RB', era: 'Current' },
    'J': { name: 'Deion Sanders', position: 'CB', era: 'Legend' },
    '10': { name: 'Drake London', position: 'WR', era: 'Current' },
    '9': { name: 'Kyle Pitts', position: 'TE', era: 'Current' },
    '8': { name: 'Jessie Bates III', position: 'S', era: 'Current' },
    '7': { name: 'Kirk Cousins', position: 'QB', era: 'Current' },
    '6': { name: 'Michael Vick', position: 'QB', era: 'Legend' },
    '5': { name: 'A.J. Terrell', position: 'CB', era: 'Current' },
    '4': { name: 'Claude Humphrey', position: 'DE', era: 'Legend' },
    '3': { name: 'Chris Lindstrom', position: 'G', era: 'Current' },
    '2': { name: 'Younghoe Koo', position: 'K', era: 'Current' }
  },
  car: {
    'A': { name: 'Cam Newton', position: 'QB', era: 'Legend' },
    'K': { name: 'Luke Kuechly', position: 'LB', era: 'Legend' },
    'Q': { name: 'Julius Peppers', position: 'DE', era: 'Legend' },
    'J': { name: 'Bryce Young', position: 'QB', era: 'Current' },
    '10': { name: 'Steve Smith Sr.', position: 'WR', era: 'Legend' },
    '9': { name: 'Derrick Brown', position: 'DT', era: 'Current' },
    '8': { name: 'Chuba Hubbard', position: 'RB', era: 'Current' },
    '7': { name: 'Brian Burns', position: 'DE', era: 'Current' },
    '6': { name: 'Jake Delhomme', position: 'QB', era: 'Legend' },
    '5': { name: 'Diontae Johnson', position: 'WR', era: 'Current' },
    '4': { name: 'Sam Mills', position: 'LB', era: 'Legend' },
    '3': { name: 'Xavier Legette', position: 'WR', era: 'Current' },
    '2': { name: 'Eddy Piñeiro', position: 'K', era: 'Current' }
  },
  no: {
    'A': { name: 'Drew Brees', position: 'QB', era: 'Legend' },
    'K': { name: 'Alvin Kamara', position: 'RB', era: 'Current' },
    'Q': { name: 'Rickey Jackson', position: 'LB', era: 'Legend' },
    'J': { name: 'Derek Carr', position: 'QB', era: 'Current' },
    '10': { name: 'Willie Roaf', position: 'OT', era: 'Legend' },
    '9': { name: 'Chris Olave', position: 'WR', era: 'Current' },
    '8': { name: 'Sammy Knight', position: 'S', era: 'Legend' },
    '7': { name: 'Rashid Shaheed', position: 'WR', era: 'Current' },
    '6': { name: 'Archie Manning', position: 'QB', era: 'Legend' },
    '5': { name: 'Cameron Jordan', position: 'DE', era: 'Current' },
    '4': { name: 'Morten Andersen', position: 'K', era: 'Legend' },
    '3': { name: 'Tyrann Mathieu', position: 'S', era: 'Current' },
    '2': { name: 'Blake Grupe', position: 'K', era: 'Current' }
  },
  tb: {
    'A': { name: 'Tom Brady', position: 'QB', era: 'Legend' },
    'K': { name: 'Derrick Brooks', position: 'LB', era: 'Legend' },
    'Q': { name: 'Mike Evans', position: 'WR', era: 'Current' },
    'J': { name: 'Warren Sapp', position: 'DT', era: 'Legend' },
    '10': { name: 'Baker Mayfield', position: 'QB', era: 'Current' },
    '9': { name: 'Lee Roy Selmon', position: 'DE', era: 'Legend' },
    '8': { name: 'Chris Godwin', position: 'WR', era: 'Current' },
    '7': { name: 'Ronde Barber', position: 'CB', era: 'Legend' },
    '6': { name: 'John Lynch', position: 'S', era: 'Legend' },
    '5': { name: 'Rachaad White', position: 'RB', era: 'Current' },
    '4': { name: 'Simeon Rice', position: 'DE', era: 'Legend' },
    '3': { name: 'Antoine Winfield Jr.', position: 'S', era: 'Current' },
    '2': { name: 'Chase McLaughlin', position: 'K', era: 'Current' }
  }
};

export const getAllTeams = () => NFL_TEAMS;

export const getTeamRoster = (teamId) => TEAM_ROSTERS[teamId] || null;

export const getTeamName = (teamId) => {
  const team = NFL_TEAMS.find(t => t.id === teamId);
  return team ? team.name : 'Unknown Team';
};

export const getTeamEmoji = (teamId) => {
  const team = NFL_TEAMS.find(t => t.id === teamId);
  return team ? team.emoji : '🏈';
};
